# Eval Qwen2.5-VL final adapter trên tập valid

Notebook này giữ cấu trúc thang đo giống file zero-shot bạn đưa vào, nhưng thay phần load model bằng:

```text
Base Qwen/Qwen2.5-VL-3B-Instruct + final LoRA adapter
```

Các thang đo có trong notebook:

- Exact Match
- VQA soft accuracy
- BLEU-1
- BLEU-2
- ROUGE-L
- METEOR
- BERTScore F1
- LLM_JUDGE bằng Gemini

Notebook này **không tính eval_loss/perplexity**.

## 1. Cài thư viện

In [1]:
!pip -q install "transformers==4.51.3" "accelerate==1.6.0" "peft==0.15.2" "bitsandbytes==0.45.5" "qwen-vl-utils" "safetensors" "pillow" "tqdm" "pandas"
!pip -q install nltk rouge-score bert-score evaluate
!pip -q install google-genai

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 63.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.7/354.7 kB 22.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 411.1/411.1 kB 32.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 60.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.3/36.3 MB 32.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.7 MB/s eta 0:00:00
  Building wheel for rouge-score (setup.py) ... done

In [2]:
import os
import re
import json
import math
import time
import string
from pathlib import Path
from datetime import datetime

import torch
import pandas as pd
from tqdm.auto import tqdm

import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

print('CUDA:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
print('Torch:', torch.__version__)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

CUDA: True
GPU: Tesla T4
Torch: 2.10.0+cu128

## 2. Chuẩn bị dữ liệu valid

Mặc định dùng:

```text
/content/drive/MyDrive/Final_Deeplearning/Split/valid/valid.jsonl
/content/drive/MyDrive/Final_Deeplearning/Split/valid/images
```

Format mỗi dòng nên có các trường như: `id`, `name`, `image`, `question`, `answer`.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

# ============================================================
# CHỈNH Ở ĐÂY NẾU ĐƯỜNG DẪN CỦA BẠN KHÁC
# ============================================================
BASE_MODEL_ID = 'Qwen/Qwen2.5-VL-3B-Instruct'

FINAL_ADAPTER_DIR = Path('/content/drive/MyDrive/Final_Deeplearning/qwen25_vl_herb_qlora_10chunks/final_finetuned_adapter')

DATA_ROOT = Path('/content/drive/MyDrive/Final_Deeplearning/Split')
VALID_DIR = DATA_ROOT / 'valid'
VALID_JSONL = VALID_DIR / 'valid.jsonl'
IMAGE_ROOT = VALID_DIR
IMAGE_DIR = VALID_DIR / 'images'

OUTPUT_DIR = Path('/content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

PRED_PATH = OUTPUT_DIR / 'predictions_final_adapter_valid.jsonl'
LLM_JUDGE_PATH = OUTPUT_DIR / 'predictions_final_adapter_valid_gemini_judge.jsonl'
RESULT_CSV = OUTPUT_DIR / 'metrics_final_adapter_valid.csv'
SUMMARY_CSV = OUTPUT_DIR / 'summary_final_adapter_valid.csv'

assert FINAL_ADAPTER_DIR.exists(), f'Không thấy final adapter: {FINAL_ADAPTER_DIR}'
assert (FINAL_ADAPTER_DIR / 'adapter_config.json').exists(), f'Thiếu adapter_config.json trong: {FINAL_ADAPTER_DIR}'
assert (FINAL_ADAPTER_DIR / 'adapter_model.safetensors').exists() or (FINAL_ADAPTER_DIR / 'adapter_model.bin').exists(), f'Thiếu adapter_model trong: {FINAL_ADAPTER_DIR}'
assert VALID_JSONL.exists(), f'Không thấy valid.jsonl: {VALID_JSONL}'
assert IMAGE_DIR.exists(), f'Không thấy thư mục images: {IMAGE_DIR}'

print('BASE_MODEL_ID     :', BASE_MODEL_ID)
print('FINAL_ADAPTER_DIR:', FINAL_ADAPTER_DIR)
print('VALID_JSONL       :', VALID_JSONL)
print('IMAGE_DIR         :', IMAGE_DIR)
print('OUTPUT_DIR        :', OUTPUT_DIR)
print('PRED_PATH         :', PRED_PATH)
print('LLM_JUDGE_PATH    :', LLM_JUDGE_PATH)

Mounted at /content/drive
BASE_MODEL_ID     : Qwen/Qwen2.5-VL-3B-Instruct
FINAL_ADAPTER_DIR: /content/drive/MyDrive/Final_Deeplearning/qwen25_vl_herb_qlora_10chunks/final_finetuned_adapter
VALID_JSONL       : /content/drive/MyDrive/Final_Deeplearning/Split/valid/valid.jsonl
IMAGE_DIR         : /content/drive/MyDrive/Final_Deeplearning/Split/valid/images
OUTPUT_DIR        : /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid
PRED_PATH         : /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid.jsonl
LLM_JUDGE_PATH    : /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid_gemini_judge.jsonl

In [4]:
def read_jsonl(path):
    rows = []
    with open(path, 'r', encoding='utf-8') as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise ValueError(f'Lỗi JSONL dòng {line_no} tại {path}: {e}')
    return rows


def normalize_rel_path(p):
    p = str(p).strip().replace('\\', '/')
    while p.startswith('./'):
        p = p[2:]
    return p.lstrip('/')


def normalize_valid_row(row, idx):
    image = row.get('image') or row.get('image_path') or row.get('path') or row.get('file_name')
    question = row.get('question') or row.get('query') or row.get('prompt')
    answer = row.get('answer')

    if answer is None:
        answer = row.get('reference_answer') or row.get('ground_truth') or row.get('gt') or row.get('label') or row.get('name')

    if not image:
        raise ValueError(f'Dòng {idx} thiếu image/image_path/path/file_name: {row}')
    if not question:
        raise ValueError(f'Dòng {idx} thiếu question/query/prompt: {row}')
    if answer is None or str(answer).strip() == '':
        raise ValueError(f'Dòng {idx} thiếu answer/reference_answer/label/name: {row}')

    return {
        'id': str(row.get('id', f'valid_{idx:06d}')),
        'plant_id': str(row.get('plant_id', row.get('id', ''))),
        'name': str(row.get('name', '')),
        'image': normalize_rel_path(image),
        'question': str(question).strip(),
        'answer': answer if isinstance(answer, list) else str(answer).strip(),
    }


def resolve_image_path(image_rel):
    image_rel = normalize_rel_path(image_rel)
    p = Path(image_rel)

    candidates = []
    if p.is_absolute():
        candidates.append(p)

    candidates.extend([
        VALID_DIR / image_rel,
        IMAGE_DIR / image_rel,
        IMAGE_DIR / p.name,
        DATA_ROOT / image_rel,
    ])

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError(
        'Không tìm thấy ảnh.\n'
        f'image trong JSONL: {image_rel}\n'
        'Đã thử:\n' + '\n'.join(str(x) for x in candidates)
    )


raw_rows = read_jsonl(VALID_JSONL)
data = [normalize_valid_row(row, idx) for idx, row in enumerate(raw_rows, start=1)]

missing = []
for r in data[:200]:
    try:
        _ = resolve_image_path(r['image'])
    except Exception as e:
        missing.append((r['image'], repr(e)))

print('Số QA trong valid:', len(data))
print('Số ảnh unique:', len({r['image'] for r in data}))
print('Số ảnh thiếu trong 200 dòng đầu:', len(missing))
if missing:
    print('Ví dụ thiếu:', missing[0])

data[:3]

Số QA trong valid: 2980
Số ảnh unique: 376
Số ảnh thiếu trong 200 dòng đầu: 0

[{'id': 'P000000312',
  'plant_id': 'P000000312',
  'name': 'Dế dũi',
  'image': 'images/P000000312.png',
  'question': 'Tên dược liệu trong ảnh là gì?',
  'answer': 'Dế dũi'},
 {'id': 'P000000312',
  'plant_id': 'P000000312',
  'name': 'Dế dũi',
  'image': 'images/P000000312.png',
  'question': 'Dược liệu Dế dũi có công dụng gì theo thông tin được cung cấp?',
  'answer': 'Chữa đau khắp mình mẩy'},
 {'id': 'P000000312',
  'plant_id': 'P000000312',
  'name': 'Dế dũi',
  'image': 'images/P000000312.png',
  'question': 'Con dế trong ảnh có màu sắc chủ đạo là gì?',
  'answer': 'Màu nâu vàng và nâu đậm'}]

## 3. Load Qwen2.5-VL-3B-Instruct + final LoRA adapter

In [5]:
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration, BitsAndBytesConfig
from peft import PeftModel
from qwen_vl_utils import process_vision_info

os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

LOAD_IN_4BIT = True
MIN_PIXELS = 64 * 28 * 28
MAX_PIXELS = 256 * 28 * 28

# Processor ưu tiên load từ adapter để giữ đúng chat template/processor đã lưu khi fine-tune.
try:
    processor = AutoProcessor.from_pretrained(
        str(FINAL_ADAPTER_DIR),
        trust_remote_code=True,
        min_pixels=MIN_PIXELS,
        max_pixels=MAX_PIXELS,
    )
    print('Loaded processor from adapter:', FINAL_ADAPTER_DIR)
except Exception as e:
    print('Không load được processor từ adapter, fallback base model:', repr(e))
    processor = AutoProcessor.from_pretrained(
        BASE_MODEL_ID,
        trust_remote_code=True,
        min_pixels=MIN_PIXELS,
        max_pixels=MAX_PIXELS,
    )

if hasattr(processor, 'tokenizer'):
    processor.tokenizer.padding_side = 'right'

quantization_config = None
if LOAD_IN_4BIT:
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type='nf4',
        bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_available() and torch.cuda.is_bf16_supported() else torch.float16,
        bnb_4bit_use_double_quant=True,
    )

base_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    BASE_MODEL_ID,
    quantization_config=quantization_config,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map='auto',
    trust_remote_code=True,
)

model = PeftModel.from_pretrained(
    base_model,
    str(FINAL_ADAPTER_DIR),
    is_trainable=False,
)

model.eval()
print('Loaded base model:', BASE_MODEL_ID)
print('Loaded final adapter:', FINAL_ADAPTER_DIR)
print('Model class:', type(model))

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

Loaded processor from adapter: /content/drive/MyDrive/Final_Deeplearning/qwen25_vl_herb_qlora_10chunks/final_finetuned_adapter

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/3.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.53G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/216 [00:00<?, ?B/s]

Loaded base model: Qwen/Qwen2.5-VL-3B-Instruct
Loaded final adapter: /content/drive/MyDrive/Final_Deeplearning/qwen25_vl_herb_qlora_10chunks/final_finetuned_adapter
Model class: <class 'peft.peft_model.PeftModelForCausalLM'>

## 4. Hàm dự đoán

Prompt giữ cùng kiểu zero-shot bạn đưa vào: trả lời ngắn bằng tiếng Việt, tối đa 10 từ.

In [6]:
def build_prompt(question):
    return (
        'Bạn là hệ thống hỏi đáp ảnh dược liệu Việt Nam. '
        'Hãy trả lời câu hỏi bằng tiếng Việt, thật ngắn gọn, tối đa 10 từ. '
        'Không giải thích thêm.\n'
        f'Câu hỏi: {question}'
    )


@torch.inference_mode()
def qwen_vl_predict(image_path, question, max_new_tokens=32):
    messages = [
        {
            'role': 'user',
            'content': [
                {'type': 'image', 'image': str(image_path)},
                {'type': 'text', 'text': build_prompt(question)},
            ],
        }
    ]

    text = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    image_inputs, video_inputs = process_vision_info(messages)

    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors='pt',
    )

    if torch.cuda.is_available():
        inputs = inputs.to('cuda')

    generated_ids = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
    )

    generated_ids_trimmed = [
        out_ids[len(in_ids):]
        for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]

    output_text = processor.batch_decode(
        generated_ids_trimmed,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )[0]

    return output_text.strip()

In [ ]:
# Test nhanh 1 mẫu.
sample = data[4]
sample_image = resolve_image_path(sample['image'])
print('Image       :', sample_image)
print('Question    :', sample['question'])
print('Ground truth:', sample['answer'])
assert sample_image.exists(), f'Không thấy ảnh: {sample_image}'
print('Prediction  :', qwen_vl_predict(sample_image, sample['question']))

Image       : /content/drive/MyDrive/Final_Deeplearning/Split/valid/images/P000000312.png
Question    : Cánh của con dế có hoa văn gì không?
Ground truth: Có

/usr/local/lib/python3.12/dist-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `1e-06` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Prediction  : Có

## 5. Chạy inference trên valid set

Prediction được lưu dần vào JSONL. Nếu Colab ngắt, chạy lại sẽ tự bỏ qua mẫu đã có.

In [7]:
MAX_SAMPLES = None  # đổi thành 20 để test nhanh, None để chạy toàn bộ valid
RESET_PREDICTIONS = False  # đổi True nếu muốn xóa prediction cũ và chạy lại từ đầu

if RESET_PREDICTIONS and PRED_PATH.exists():
    PRED_PATH.unlink()
    print('Đã xóa prediction cũ:', PRED_PATH)

eval_data = data[:MAX_SAMPLES] if MAX_SAMPLES is not None else data
print('Số mẫu sẽ chạy:', len(eval_data))
print('PRED_PATH:', PRED_PATH)

Số mẫu sẽ chạy: 2980
PRED_PATH: /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid.jsonl

In [8]:
done_keys = set()
if PRED_PATH.exists():
    for row in read_jsonl(PRED_PATH):
        done_keys.add((str(row.get('id')), str(row.get('image')), str(row.get('question'))))
print('Đã có prediction:', len(done_keys))

with open(PRED_PATH, 'a', encoding='utf-8') as f:
    for row in tqdm(eval_data):
        key = (str(row.get('id')), str(row.get('image')), str(row.get('question')))
        if key in done_keys:
            continue

        image_path = resolve_image_path(row['image'])
        try:
            pred = qwen_vl_predict(image_path, row['question'])
            error = ''
        except Exception as e:
            pred = ''
            error = repr(e)

        out = dict(row)
        out['prediction'] = pred
        out['error'] = error
        out['model_id'] = BASE_MODEL_ID
        out['adapter_dir'] = str(FINAL_ADAPTER_DIR)
        out['created_at'] = datetime.now().isoformat()

        f.write(json.dumps(out, ensure_ascii=False) + '\n')
        f.flush()

print('Saved:', PRED_PATH)

Đã có prediction: 2980

  0%|          | 0/2980 [00:00<?, ?it/s]

Saved: /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid.jsonl

## 6. Metric: Exact Match và VQA soft accuracy

In [9]:
VI_PUNCT = string.punctuation + '“”‘’…–—。、，！？：；（）[]{}'


def normalize_answer(s):
    if s is None:
        return ''
    s = str(s).lower().strip()
    s = re.sub(r'[{}]'.format(re.escape(VI_PUNCT)), ' ', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def exact_match(pred, refs):
    if isinstance(refs, str):
        refs = [refs]
    pred_n = normalize_answer(pred)
    return float(any(pred_n == normalize_answer(ref) for ref in refs))


def vqa_v2_soft_accuracy(pred, refs):
    if isinstance(refs, str):
        return exact_match(pred, refs)

    pred_n = normalize_answer(pred)
    refs_n = [normalize_answer(r) for r in refs]
    if len(refs_n) <= 1:
        return float(pred_n == refs_n[0]) if refs_n else 0.0

    scores = []
    for i, _ in enumerate(refs_n):
        others = refs_n[:i] + refs_n[i+1:]
        matches = sum(pred_n == ans for ans in others)
        scores.append(min(1.0, matches / 3.0))
    return sum(scores) / len(scores)

## 7. Metric: BLEU, ROUGE-L, METEOR, BERTScore

In [10]:
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.translate.meteor_score import meteor_score
from rouge_score import rouge_scorer
from bert_score import score as bert_score

smooth = SmoothingFunction().method1
rouge = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)


def first_ref(refs):
    return refs[0] if isinstance(refs, list) else refs


def tokenized(text):
    return normalize_answer(text).split()


def bleu_1(pred, ref):
    return sentence_bleu([tokenized(ref)], tokenized(pred), weights=(1.0, 0, 0, 0), smoothing_function=smooth)


def bleu_2(pred, ref):
    return sentence_bleu([tokenized(ref)], tokenized(pred), weights=(0.5, 0.5, 0, 0), smoothing_function=smooth)


def rouge_l(pred, ref):
    return rouge.score(ref, pred)['rougeL'].fmeasure


def meteor(pred, ref):
    try:
        return meteor_score([tokenized(ref)], tokenized(pred))
    except Exception:
        return 0.0

## 8. LLM-as-a-judge bằng Gemini API

Cell này chấm prediction đã sinh bằng Gemini. Chỉ cần dán API key vào biến `GEMINI_API_KEY`.

Kết quả lưu vào:

```text
predictions_final_adapter_valid_gemini_judge.jsonl
```

In [11]:
# ============================================================
# 8. LLM-AS-A-JUDGE BẰNG GEMINI CÓ RETRY + RESUME
# Sửa đúng 1 biến: GEMINI_API_KEY
# ============================================================

import json
import time
import random
from pathlib import Path
from tqdm.auto import tqdm

from google import genai
from google.genai import types


# ============================================================
# A. CONFIG
# ============================================================

GEMINI_API_KEY = "AIzaSyC-pUDVzAjEn8o1WQN89R5oHRV5HZOF90w"

# Giữ nguyên model Gemini bạn đang dùng, không đổi sang model khác.
JUDGE_MODEL = "gemini-3.1-flash-lite-preview"
# JUDGE_MODEL = "gemini-2.5-flash"
MAX_JUDGE_SAMPLES = None       # None = chấm toàn bộ prediction
BATCH_SIZE = 10               # giảm từ 10 xuống 3 để ít dính 503 hơn
SLEEP_SECONDS = 15             # nghỉ giữa các batch
RESET_LLM_JUDGE_OUTPUT = False # True = xóa kết quả cũ và chấm lại từ đầu
LIST_AVAILABLE_MODELS = False

MAX_RETRIES = 8                # số lần retry khi 503/429
BASE_RETRY_SLEEP = 10          # giây
MAX_RETRY_SLEEP = 180          # giây

print("Judge model:", JUDGE_MODEL)
print("BATCH_SIZE:", BATCH_SIZE)
print("SLEEP_SECONDS:", SLEEP_SECONDS)
print("MAX_RETRIES:", MAX_RETRIES)


# ============================================================
# B. CHECK API + CLIENT
# ============================================================

if not GEMINI_API_KEY or GEMINI_API_KEY == "DAN_API_KEY_CUA_BAN_VAO_DAY":
    raise ValueError("Bạn chưa dán API key vào biến GEMINI_API_KEY ở đầu cell.")

client = genai.Client(api_key=GEMINI_API_KEY)

if LIST_AVAILABLE_MODELS:
    models = client.models.list()
    for m in models:
        print(f"{getattr(m, 'name', '')} | {getattr(m, 'display_name', '')}")

if not PRED_PATH.exists():
    raise FileNotFoundError(f"Chưa có file prediction: {PRED_PATH}. Hãy chạy cell inference trước.")

print("Input :", PRED_PATH)
print("Output:", LLM_JUDGE_PATH)


# ============================================================
# C. HÀM ĐỌC/GHI JSONL AN TOÀN
# ============================================================

def read_jsonl_safe(path):
    path = Path(path)
    rows = []

    if not path.exists():
        return rows

    bad_lines = []

    with path.open("r", encoding="utf-8") as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue

            try:
                rows.append(json.loads(line))
            except Exception as e:
                bad_lines.append((line_no, repr(e), line[:300]))

    if bad_lines:
        print(f"[WARNING] {path.name}: có {len(bad_lines)} dòng JSON lỗi. In tối đa 5 dòng:")
        for x in bad_lines[:5]:
            print(x)

    return rows


def write_jsonl_atomic(rows, path):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    tmp_path = path.with_suffix(path.suffix + ".tmp")

    with tmp_path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    tmp_path.replace(path)


def get_row_id(row, fallback_index=None):
    rid = row.get("id", None)
    if rid is None or str(rid).strip() == "":
        return f"row_{fallback_index:06d}"
    return str(rid)


# ============================================================
# D. LẤY GROUND TRUTH / PREDICTION
# ============================================================

def get_ground_truth(row):
    # Ưu tiên reference_answer trước.
    # Nếu không có thì mới fallback sang answer/label.
    for key in ["reference_answer", "ground_truth", "gt", "label", "answer"]:
        value = row.get(key)
        if value is not None and str(value).strip():
            if isinstance(value, list):
                return str(value[0]).strip() if value else ""
            return str(value).strip()
    return ""


def get_prediction(row):
    for key in ["prediction", "pred", "model_answer", "generated_answer", "output", "response"]:
        value = row.get(key)
        if value is not None and str(value).strip():
            return str(value).strip()

    # Một số file eval dùng "answer" làm output model.
    # Chỉ dùng answer làm prediction nếu không có reference_answer trùng vai trò.
    if "reference_answer" in row and row.get("answer") is not None:
        return str(row.get("answer")).strip()

    return ""


def clean_json_text(text):
    text = str(text).strip()

    if text.startswith("```json"):
        text = text.replace("```json", "", 1).strip()

    if text.startswith("```"):
        text = text.replace("```", "", 1).strip()

    if text.endswith("```"):
        text = text[:-3].strip()

    return text.strip()


# ============================================================
# E. LOAD PREDICTIONS + RESUME
# ============================================================

pred_rows_all = read_jsonl_safe(PRED_PATH)

# Chỉ giữ dòng có prediction hợp lệ.
valid_pred_rows = []
for idx, r in enumerate(pred_rows_all, start=1):
    pred = get_prediction(r)
    gt = get_ground_truth(r)

    if pred and gt:
        rr = dict(r)
        rr["_judge_internal_id"] = get_row_id(rr, idx)
        valid_pred_rows.append(rr)

pred_rows = valid_pred_rows[:MAX_JUDGE_SAMPLES] if MAX_JUDGE_SAMPLES is not None else valid_pred_rows

if len(pred_rows) == 0:
    raise ValueError("File prediction rỗng hoặc thiếu prediction/ground_truth hợp lệ.")

if RESET_LLM_JUDGE_OUTPUT and LLM_JUDGE_PATH.exists():
    LLM_JUDGE_PATH.unlink()
    print("Đã xóa file judge cũ để chấm lại từ đầu.")

old_rows = read_jsonl_safe(LLM_JUDGE_PATH)

# Map kết quả cũ theo id.
old_by_id = {}
for r in old_rows:
    rid = str(r.get("_judge_internal_id") or r.get("id") or "")
    if rid:
        old_by_id[rid] = r

# Khởi tạo result_by_id:
# - Nếu đã có score hợp lệ thì giữ kết quả cũ.
# - Nếu chưa có thì dùng row prediction gốc.
result_by_id = {}
target_ids_order = []

for idx, r in enumerate(pred_rows, start=1):
    rid = str(r["_judge_internal_id"])
    target_ids_order.append(rid)

    old = old_by_id.get(rid)
    if old is not None and old.get("gemini_judge_score") is not None:
        result_by_id[rid] = old
    else:
        base = dict(r)
        base.pop("_judge_internal_id", None)
        base["_judge_internal_id"] = rid
        result_by_id[rid] = base

done_ids = {
    rid
    for rid, r in result_by_id.items()
    if r.get("gemini_judge_score") is not None
}

rows_to_judge = [
    r
    for r in pred_rows
    if str(r["_judge_internal_id"]) not in done_ids
]

print("Tổng số dòng cần có:", len(pred_rows))
print("Đã chấm hợp lệ trước đó:", len(done_ids))
print("Còn lại cần chấm:", len(rows_to_judge))


# Ghi lại file hiện tại để chuẩn hóa format và tránh mất resume.
write_jsonl_atomic(
    [result_by_id[rid] for rid in target_ids_order],
    LLM_JUDGE_PATH
)


# ============================================================
# F. RETRY CHO GEMINI 503/429
# ============================================================

RETRYABLE_KEYWORDS = [
    "503",
    "unavailable",
    "high demand",
    "429",
    "resource_exhausted",
    "quota",
    "rate limit",
    "timeout",
    "temporarily",
    "deadline",
    "internal",
    "500",
    "502",
    "504",
]


def is_retryable_gemini_error(e):
    msg = str(e).lower()
    return any(k.lower() in msg for k in RETRYABLE_KEYWORDS)


def call_gemini_with_retry(call_fn, max_retries=MAX_RETRIES):
    last_error = None

    for attempt in range(max_retries):
        try:
            return call_fn()

        except Exception as e:
            last_error = e

            if not is_retryable_gemini_error(e):
                raise

            sleep_time = min(
                MAX_RETRY_SLEEP,
                BASE_RETRY_SLEEP * (2 ** attempt)
            )
            sleep_time += random.uniform(0, 5)

            print(f"[Gemini retry {attempt + 1}/{max_retries}] {repr(e)}")
            print(f"Đợi {sleep_time:.1f}s rồi thử lại...")
            time.sleep(sleep_time)

    raise last_error


# ============================================================
# G. HÀM JUDGE 1 BATCH
# ============================================================

def build_judge_prompt(batch):
    items = []

    for i, row in enumerate(batch):
        items.append({
            "index": i,
            "question": str(row.get("question", "")).strip(),
            "ground_truth": get_ground_truth(row),
            "prediction": get_prediction(row),
        })

    prompt = f"""
Bạn là giám khảo cho bài toán Visual Question Answering tiếng Việt về dược liệu.

Nhiệm vụ:
Chấm từng prediction có đúng nghĩa với ground_truth hay không.

Quy tắc chấm:
- score = 1 nếu prediction đúng hoặc tương đương nghĩa với ground_truth.
- score = 0 nếu prediction sai nghĩa.
- Chấp nhận cách diễn đạt tương đương.
- Ví dụ: "Trắng" tương đương "Màu trắng".
- Ví dụ: "Hồ điệp" tương đương "Cây hồ điệp".
- Ví dụ: "Rau má" tương đương "Cây rau má".
- Không yêu cầu prediction giống từng chữ với ground_truth.
- Không giải thích.
- Chỉ trả về JSON hợp lệ.

Dữ liệu cần chấm:
{json.dumps(items, ensure_ascii=False)}

Trả về đúng dạng JSON list:
[
  {{"index": 0, "score": 1}},
  {{"index": 1, "score": 0}}
]
""".strip()

    return prompt


def parse_judge_response(text, batch_size):
    text = clean_json_text(text)
    parsed = json.loads(text)

    if isinstance(parsed, dict):
        if "results" in parsed:
            parsed = parsed["results"]
        elif "scores" in parsed:
            parsed = parsed["scores"]
        else:
            parsed = [parsed]

    if not isinstance(parsed, list):
        raise ValueError(f"Gemini không trả về JSON list. Response: {text[:500]}")

    scores = [None] * batch_size

    for obj in parsed:
        idx = int(obj["index"])
        score = int(obj["score"])

        if 0 <= idx < batch_size:
            scores[idx] = 1 if score == 1 else 0

    return scores


def judge_batch_gemini(batch):
    prompt = build_judge_prompt(batch)

    try:
        resp = call_gemini_with_retry(
            lambda: client.models.generate_content(
                model=JUDGE_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0,
                    response_mime_type="application/json",
                ),
            )
        )

        scores = parse_judge_response(resp.text, len(batch))
        errors = [None] * len(batch)
        return scores, errors

    except Exception as e:
        print("Gemini judge batch lỗi:", repr(e))

        # Nếu batch > 1, fallback chấm từng dòng.
        # Cách này chậm hơn nhưng giảm rủi ro JSON lỗi hoặc payload quá dài.
        if len(batch) > 1:
            print("[FALLBACK] Chấm từng dòng trong batch...")
            all_scores = []
            all_errors = []

            for row in batch:
                s, err = judge_batch_gemini([row])
                all_scores.append(s[0])
                all_errors.append(err[0])
                time.sleep(SLEEP_SECONDS)

            return all_scores, all_errors

        return [None], [repr(e)]


# ============================================================
# H. CHẤM VÀ RESUME THEO TỪNG BATCH
# ============================================================

for start in tqdm(range(0, len(rows_to_judge), BATCH_SIZE), desc="Gemini Judge"):
    batch = rows_to_judge[start:start + BATCH_SIZE]

    scores, errors = judge_batch_gemini(batch)

    for row, score, err in zip(batch, scores, errors):
        rid = str(row["_judge_internal_id"])

        new_row = dict(row)
        new_row.pop("_judge_internal_id", None)
        new_row["_judge_internal_id"] = rid

        new_row["gemini_judge_score"] = score
        new_row["judge_model"] = JUDGE_MODEL
        new_row["judge_error"] = err
        new_row["judge_created_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        result_by_id[rid] = new_row

    # Ghi lại sau mỗi batch để nếu Colab bị ngắt thì vẫn resume được.
    write_jsonl_atomic(
        [result_by_id[rid] for rid in target_ids_order],
        LLM_JUDGE_PATH
    )

    valid_now = sum(
        1
        for rid in target_ids_order
        if result_by_id[rid].get("gemini_judge_score") is not None
    )

    print(f"[SAVE] Đã chấm hợp lệ: {valid_now}/{len(pred_rows)} -> {LLM_JUDGE_PATH}")

    time.sleep(SLEEP_SECONDS)


# ============================================================
# I. TỔNG KẾT
# ============================================================

judge_rows = read_jsonl_safe(LLM_JUDGE_PATH)

target_ids = set(target_ids_order)
judge_rows = [
    r for r in judge_rows
    if str(r.get("_judge_internal_id") or r.get("id") or "") in target_ids
]

valid_scores = [
    int(r["gemini_judge_score"])
    for r in judge_rows
    if r.get("gemini_judge_score") is not None
]

failed_rows = [
    r for r in judge_rows
    if r.get("gemini_judge_score") is None
]

print("=" * 80)
print("Saved:", LLM_JUDGE_PATH)
print("Đã chấm hợp lệ:", len(valid_scores), "/", len(pred_rows))
print("Còn lỗi/chưa chấm:", len(failed_rows))

if valid_scores:
    print("Gemini Judge Accuracy:", sum(valid_scores) / len(valid_scores))
else:
    print("Không có score hợp lệ.")

if failed_rows:
    print("\nMột vài dòng chưa chấm được:")
    for r in failed_rows[:5]:
        print({
            "id": r.get("id"),
            "judge_error": r.get("judge_error"),
        })

Judge model: gemini-3.1-flash-lite-preview
BATCH_SIZE: 10
SLEEP_SECONDS: 15
MAX_RETRIES: 8
Input : /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid.jsonl
Output: /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid_gemini_judge.jsonl
Tổng số dòng cần có: 2980
Đã chấm hợp lệ trước đó: 376
Còn lại cần chấm: 0

Gemini Judge: 0it [00:00, ?it/s]

================================================================================
Saved: /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/predictions_final_adapter_valid_gemini_judge.jsonl
Đã chấm hợp lệ: 2980 / 2980
Còn lỗi/chưa chấm: 0
Gemini Judge Accuracy: 0.487248322147651

## 9. Tổng hợp kết quả

In [12]:
pred_rows = read_jsonl(PRED_PATH)
pred_rows = [r for r in pred_rows if r.get('prediction') is not None]
print('Loaded predictions:', len(pred_rows))

records = []
for r in pred_rows:
    ref = first_ref(r['answer'])
    pred = r.get('prediction', '')
    records.append({
        'id': r.get('id', ''),
        'image': r.get('image', ''),
        'question': r.get('question', ''),
        'answer': ref,
        'prediction': pred,
        'exact_match': exact_match(pred, r['answer']),
        'vqa_soft_acc': vqa_v2_soft_accuracy(pred, r['answer']),
        'bleu_1': bleu_1(pred, ref),
        'bleu_2': bleu_2(pred, ref),
        'rouge_l': rouge_l(pred, ref),
        'meteor': meteor(pred, ref),
        'error': r.get('error', ''),
    })

df = pd.DataFrame(records)
df.head()

Loaded predictions: 2980

,id,image,question,answer,prediction,exact_match,vqa_soft_acc,bleu_1,bleu_2,rouge_l,meteor,error
0,P000000312,images/P000000312.png,Tên dược liệu trong ảnh là gì?,Dế dũi,Đó là vị thuốc bọ chét,0.0,0.0,0.000000,0.000000,0.000000,0.000000,
1,P000000312,images/P000000312.png,Dược liệu Dế dũi có công dụng gì theo thông ti...,Chữa đau khắp mình mẩy,Chữa sốt,0.0,0.0,0.111565,0.049893,0.307692,0.106383,
2,P000000312,images/P000000312.png,Con dế trong ảnh có màu sắc chủ đạo là gì?,Màu nâu vàng và nâu đậm,Màu nâu vàng,0.0,0.0,0.367879,0.367879,0.750000,0.263158,
3,P000000312,images/P000000312.png,Phần đầu của con dế có đặc điểm gì nổi bật?,Phần đầu của con dế có kích thước lớn và,Phần đầu của con dế có hai chiếc bướm dài,0.0,0.0,0.600000,0.577350,0.600000,0.598611,
4,P000000312,images/P000000312.png,Cánh của con dế có hoa văn gì không?,Có,Có,1.0,1.0,1.000000,0.316228,1.000000,0.500000,

In [13]:
# BERTScore chạy theo batch, có thể hơi lâu lần đầu vì tải model xlm-roberta-base.
preds = df['prediction'].fillna('').tolist()
refs = df['answer'].fillna('').tolist()

if len(df) > 0:
    P, R, F1 = bert_score(
        preds,
        refs,
        lang='vi',
        model_type='xlm-roberta-base',
        verbose=True,
        rescale_with_baseline=False,
    )
    df['bertscore_precision'] = P.cpu().numpy()
    df['bertscore_recall'] = R.cpu().numpy()
    df['bertscore_f1'] = F1.cpu().numpy()
else:
    df['bertscore_precision'] = []
    df['bertscore_recall'] = []
    df['bertscore_f1'] = []

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

calculating scores...
computing bert embedding.

  0%|          | 0/48 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/47 [00:00<?, ?it/s]

done in 3.59 seconds, 829.35 sentences/sec

In [14]:
# Gộp kết quả Gemini judge đã lưu vào dataframe df.
# Cell này KHÔNG gọi API nữa.

if Path(LLM_JUDGE_PATH).exists():
    judge_rows = read_jsonl(LLM_JUDGE_PATH)
    judge_map = {
        str(r.get('id', '')): r.get('gemini_judge_score')
        for r in judge_rows
        if r.get('gemini_judge_score') is not None
    }

    df['llm_judge'] = df['id'].astype(str).map(judge_map)
    print('Đã gộp llm_judge:', df['llm_judge'].notna().sum(), '/', len(df))
else:
    df['llm_judge'] = math.nan
    print('Chưa có file Gemini judge. Chạy cell LLM-as-a-judge trước nếu muốn có metric này.')

Đã gộp llm_judge: 2980 / 2980

In [15]:
metric_cols = [
    'exact_match',
    'vqa_soft_acc',
    'bleu_1',
    'bleu_2',
    'rouge_l',
    'meteor',
    'bertscore_f1',
    'llm_judge',
]

summary = df[metric_cols].mean(numeric_only=True).to_frame('score')
summary

                 score
exact_match   0.179866
vqa_soft_acc  0.179866
bleu_1        0.400636
bleu_2        0.258793
rouge_l       0.497175
meteor        0.326298
bertscore_f1  0.880050
llm_judge     0.487248

In [16]:
df.to_csv(RESULT_CSV, index=False, encoding='utf-8-sig')
summary.to_csv(SUMMARY_CSV, encoding='utf-8-sig')

print('Saved detail :', RESULT_CSV)
print('Saved summary:', SUMMARY_CSV)
print('\nSummary:')
print(summary)

Saved detail : /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/metrics_final_adapter_valid.csv
Saved summary: /content/drive/MyDrive/Final_Deeplearning/eval_final_adapter_valid/summary_final_adapter_valid.csv

Summary:
                 score
exact_match   0.179866
vqa_soft_acc  0.179866
bleu_1        0.400636
bleu_2        0.258793
rouge_l       0.497175
meteor        0.326298
bertscore_f1  0.880050
llm_judge     0.487248

## 10. Xem ví dụ đúng/sai

In [17]:
cols = ['image', 'question', 'answer', 'prediction', 'exact_match', 'vqa_soft_acc', 'bertscore_f1', 'llm_judge']
existing_cols = [c for c in cols if c in df.columns]
df[existing_cols].sort_values('exact_match', ascending=True).head(10)

,image,question,answer,prediction,exact_match,vqa_soft_acc,bertscore_f1,llm_judge
1669,images/P000000411.png,Bộ phận nào nổi bật nhất trong bức ảnh này?,Bộ phận nổi bật nhất trong ảnh là các lá,Bộ phận nổi bật nhất là các lá của cây,0.0,0.0,0.944674,1
1658,images/P000000410.png,Hình dạng của các lá trong ảnh như thế nào?,Các lá có hình bầu dục hoặc hình trứng nhỏ,Các lá có hình bầu dục hoặc hình trứng,0.0,0.0,0.986330,1
2692,images/P000000003.jpg,Các lá mọc theo dạng gì?,"Các lá mọc thành dạng khóm, tỏa ra từ gốc",Các lá mọc đối xứng nhau ở phần gốc,0.0,0.0,0.880204,1
1660,images/P000000411.png,Tên dược liệu trong ảnh là gì?,Mã biên thảo,Đậu xanh,0.0,0.0,0.842817,1
1661,images/P000000411.png,Dược liệu Mã biên thảo có công dụng gì theo th...,Dùng cho trẻ em suy dinh dưỡng,Chữa viêm gan,0.0,0.0,0.798396,1
1664,images/P000000411.png,Các lá trong ảnh mọc theo dạng gì?,Các lá mọc thành từng cụm nhỏ trên thân cây,Mọc đối xứng nhau trên cành,0.0,0.0,0.815093,1
1665,images/P000000411.png,Thân cây trong ảnh có màu gì?,Màu xanh nhạt,Màu xanh lục,0.0,0.0,0.976354,1
1666,images/P000000411.png,Các lá cây trong ảnh có bề mặt trông như thế nào?,Bề mặt lá trông khá mịn và phẳng,Các lá cây có bề mặt trông khá nhẵn và,0.0,0.0,0.871834,1
2689,images/P000000003.jpg,Dược liệu Cao cẳng lá mác có công dụng gì theo...,Dùng trị tim đập mạnh,Chữa viêm gan,0.0,0.0,0.813729,1
1668,images/P000000411.png,Các lá ở phía bên phải ảnh có kích thước lớn h...,Các lá ở phía bên phải ảnh có vẻ lớn,Các lá ở phía bên phải có kích thước lớn hơn,0.0,0.0,0.940607,1